/**
 * Play&Go HSC Project
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * Contact: info@smartcommunitylab.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { environment } from 'src/environments/environment';
import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable } from 'rxjs';

import { UserConsent } from '../model/userConsent';

@Injectable({
  providedIn: 'root',
})
export class UserControllerService {
  constructor(private http: HttpClient) {}
  /**
   * getUserConsent
   *
   */
  public getUserConsentUsingGET(): Observable<UserConsent> {
    return this.http.request<UserConsent>(
      'get',
      environment.serverUrl.hscApi + `/playandgo-hsc/api/user/consent`,
      {}
    );
  }

  /**
   * updateConsent
   *
   * @param privacy privacy
   */
  public updateConsentUsingPUT(privacy: boolean): Observable<UserConsent> {
    return this.http.request<UserConsent>(
      'put',
      environment.serverUrl.hscApi + `/playandgo-hsc/api/user/consent`,
      {
        params: removeNullOrUndefined({
          privacy,
        }),
      }
    );
  }
}

function removeNullOrUndefined(obj: any) {
  const newObj: any = {};
  Object.keys(obj).forEach((key) => {
    if (obj[key] != null) {
      newObj[key] = obj[key];
    }
  });
  return newObj;
}
