/**
 * Play&Go HSC Project
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * Contact: info@smartcommunitylab.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { environment } from 'src/environments/environment';
import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable } from 'rxjs';

import { CampaignPlacing } from '../model/campaignPlacing';
import { GameStats } from '../model/gameStats';
import { PageCampaignPlacing } from '../model/pageCampaignPlacing';
import { PlacingComparison } from '../model/placingComparison';
import { TransportStat } from '../model/transportStat';

@Injectable({
  providedIn: 'root',
})
export class TeamStatsControllerService {
  constructor(private http: HttpClient) {}
  /**
   * geGroupCampaingPlacingByTransportMode
   *
   * @param campaignId campaignId
   * @param groupId groupId
   * @param metric metric
   * @param mean mean
   * @param dateFrom yyyy-MM-dd
   * @param dateTo yyyy-MM-dd
   */
  public geGroupCampaingPlacingByTransportModeUsingGET(args: {
    campaignId: string;
    groupId: string;
    metric: string;
    mean?: string;
    dateFrom?: string;
    dateTo?: string;
  }): Observable<CampaignPlacing> {
    const { campaignId, groupId, metric, mean, dateFrom, dateTo } = args;
    return this.http.request<CampaignPlacing>(
      'get',
      environment.serverUrl.hscApi +
        `/playandgo-hsc/api/data/campaign/placing/group/transport`,
      {
        params: removeNullOrUndefined({
          campaignId,
          groupId,
          metric,
          mean,
          dateFrom,
          dateTo,
        }),
      }
    );
  }

  /**
   * getCampaignPlacingByGameGroupComparison
   *
   * @param campaignId campaignId
   * @param groupId groupId
   * @param dateFrom yyyy-MM-dd
   * @param dateTo yyyy-MM-dd
   */
  public getCampaignPlacingByGameGroupComparisonUsingGET(args: {
    campaignId: string;
    groupId: string;
    dateFrom?: string;
    dateTo?: string;
  }): Observable<PlacingComparison> {
    const { campaignId, groupId, dateFrom, dateTo } = args;
    return this.http.request<PlacingComparison>(
      'get',
      environment.serverUrl.hscApi +
        `/playandgo-hsc/api/data/campaign/placing/group/game/comparison`,
      {
        params: removeNullOrUndefined({
          campaignId,
          groupId,
          dateFrom,
          dateTo,
        }),
      }
    );
  }

  /**
   * getCampaignPlacingByGamePlayerComparison
   *
   * @param campaignId campaignId
   * @param playerId playerId
   * @param dateFrom yyyy-MM-dd
   * @param dateTo yyyy-MM-dd
   */
  public getCampaignPlacingByGamePlayerComparisonUsingGET(args: {
    campaignId: string;
    playerId: string;
    dateFrom?: string;
    dateTo?: string;
  }): Observable<PlacingComparison> {
    const { campaignId, playerId, dateFrom, dateTo } = args;
    return this.http.request<PlacingComparison>(
      'get',
      environment.serverUrl.hscApi +
        `/playandgo-hsc/api/data/campaign/placing/player/game/comparison`,
      {
        params: removeNullOrUndefined({
          campaignId,
          playerId,
          dateFrom,
          dateTo,
        }),
      }
    );
  }

  /**
   * getCampaingPlacingByGame
   *
   * @param campaignId campaignId
   * @param page Results page you want to retrieve (0..N)
   * @param size Number of records per page
   * @param sort Sorting option: field,[asc,desc]
   * @param dateFrom yyyy-MM-dd
   * @param dateTo yyyy-MM-dd
   */
  public getCampaingPlacingByGameUsingGET(args: {
    campaignId: string;
    page: number;
    size: number;
    sort?: string;
    dateFrom?: string;
    dateTo?: string;
  }): Observable<PageCampaignPlacing> {
    const { campaignId, page, size, sort, dateFrom, dateTo } = args;
    return this.http.request<PageCampaignPlacing>(
      'get',
      environment.serverUrl.hscApi +
        `/playandgo-hsc/api/data/campaign/placing/game`,
      {
        params: removeNullOrUndefined({
          campaignId,
          page,
          size,
          sort,
          dateFrom,
          dateTo,
        }),
      }
    );
  }

  /**
   * getCampaingPlacingByTransportStats
   *
   * @param campaignId campaignId
   * @param page Results page you want to retrieve (0..N)
   * @param size Number of records per page
   * @param metric metric
   * @param sort Sorting option: field,[asc,desc]
   * @param mean mean
   * @param dateFrom yyyy-MM-dd
   * @param dateTo yyyy-MM-dd
   */
  public getCampaingPlacingByTransportStatsUsingGET(args: {
    campaignId: string;
    page: number;
    size: number;
    metric: string;
    sort?: string;
    mean?: string;
    dateFrom?: string;
    dateTo?: string;
  }): Observable<PageCampaignPlacing> {
    const { campaignId, page, size, metric, sort, mean, dateFrom, dateTo } =
      args;
    return this.http.request<PageCampaignPlacing>(
      'get',
      environment.serverUrl.hscApi +
        `/playandgo-hsc/api/data/campaign/placing/transport`,
      {
        params: removeNullOrUndefined({
          campaignId,
          page,
          size,
          sort,
          metric,
          mean,
          dateFrom,
          dateTo,
        }),
      }
    );
  }

  /**
   * getGroupCampaingPlacingByGame
   *
   * @param campaignId campaignId
   * @param groupId groupId
   * @param dateFrom yyyy-MM-dd
   * @param dateTo yyyy-MM-dd
   */
  public getGroupCampaingPlacingByGameUsingGET(args: {
    campaignId: string;
    groupId: string;
    dateFrom?: string;
    dateTo?: string;
  }): Observable<CampaignPlacing> {
    const { campaignId, groupId, dateFrom, dateTo } = args;
    return this.http.request<CampaignPlacing>(
      'get',
      environment.serverUrl.hscApi +
        `/playandgo-hsc/api/data/campaign/placing/group/game`,
      {
        params: removeNullOrUndefined({
          campaignId,
          groupId,
          dateFrom,
          dateTo,
        }),
      }
    );
  }

  /**
   * getGroupGameStats
   *
   * @param campaignId campaignId
   * @param groupId groupId
   * @param groupMode groupMode
   * @param dateFrom yyyy-MM-dd
   * @param dateTo yyyy-MM-dd
   */
  public getGroupGameStatsUsingGET(args: {
    campaignId: string;
    groupId: string;
    groupMode: string;
    dateFrom: string;
    dateTo: string;
  }): Observable<Array<GameStats>> {
    const { campaignId, groupId, groupMode, dateFrom, dateTo } = args;
    return this.http.request<Array<GameStats>>(
      'get',
      environment.serverUrl.hscApi +
        `/playandgo-hsc/api/data/campaign/group/game/stats`,
      {
        params: removeNullOrUndefined({
          campaignId,
          groupId,
          groupMode,
          dateFrom,
          dateTo,
        }),
      }
    );
  }

  /**
   * getGroupTransportStatsGroupByMean
   *
   * @param campaignId campaignId
   * @param groupId groupId
   * @param metric metric
   * @param avg avg
   * @param dateFrom yyyy-MM-dd
   * @param dateTo yyyy-MM-dd
   */
  public getGroupTransportStatsGroupByMeanUsingGET(args: {
    campaignId: string;
    groupId: string;
    metric: string;
    avg?: boolean;
    dateFrom?: string;
    dateTo?: string;
  }): Observable<Array<TransportStat>> {
    const { campaignId, groupId, metric, avg, dateFrom, dateTo } = args;
    return this.http.request<Array<TransportStat>>(
      'get',
      environment.serverUrl.hscApi +
        `/playandgo-hsc/api/data/campaign/transport/group/stats/mean`,
      {
        params: removeNullOrUndefined({
          campaignId,
          groupId,
          metric,
          avg,
          dateFrom,
          dateTo,
        }),
      }
    );
  }

  /**
   * getGroupTransportStats
   *
   * @param campaignId campaignId
   * @param groupId groupId
   * @param metric metric
   * @param groupMode groupMode
   * @param mean mean
   * @param dateFrom yyyy-MM-dd
   * @param dateTo yyyy-MM-dd
   */
  public getGroupTransportStatsUsingGET(args: {
    campaignId: string;
    groupId: string;
    metric: string;
    groupMode?: string;
    mean?: string;
    dateFrom?: string;
    dateTo?: string;
  }): Observable<Array<TransportStat>> {
    const { campaignId, groupId, metric, groupMode, mean, dateFrom, dateTo } =
      args;
    return this.http.request<Array<TransportStat>>(
      'get',
      environment.serverUrl.hscApi +
        `/playandgo-hsc/api/data/campaign/transport/group/stats`,
      {
        params: removeNullOrUndefined({
          campaignId,
          groupId,
          metric,
          groupMode,
          mean,
          dateFrom,
          dateTo,
        }),
      }
    );
  }
}

function removeNullOrUndefined(obj: any) {
  const newObj: any = {};
  Object.keys(obj).forEach((key) => {
    if (obj[key] != null) {
      newObj[key] = obj[key];
    }
  });
  return newObj;
}
