/**
 * Play&Go HSC Project
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * Contact: info@smartcommunitylab.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Campaign } from './campaign';

export interface Initiative {
  bonus?: number;
  bonusThreshold?: number;
  campaign?: Campaign;
  canCreate?: boolean;
  canEdit?: boolean;
  initiativeId?: string;
  maxTeamSize?: number;
  teamLeaderDomainList?: Array<string>;
  teamLeaderList?: Array<string>;
  type?: string;
}
